name: calendaze
description: A calendar app with event scheduling and notifications
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  table_calendar: ^3.2.0
  flutter_local_notifications: ^19.0.0
  provider: ^6.1.1
  intl: ^0.20.1
  shared_preferences: ^2.2.1
  timezone: ^0.10.0
  permission_handler: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true